### ISSUE TITLE
Which BFM model needs to be downloaded？

### ISSUE THREAD

**Issue by nicongger** [Fictionarry/ER-NeRF#107]
![bf7e7def-f2b0-49a5-8603-db4b745ee9b6](https://github.com/Fictionarry/ER-NeRF/assets/152894389/b2d6d3a9-d3f7-4421-a0e6-331aaf083c9a)
when I go to this step, I meet a trouble, I didn't find .mat files in the email
![25401941-c3cb-4212-be85-b4594d9f3349](https://github.com/Fictionarry/ER-NeRF/assets/152894389/84a180b2-45c8-42de-819d-4ea4c7dbd738)
there are many available models here, which I need to download?

**Comment by FredWe** [comment]
Use this one: 
https://drive.google.com/uc?id=1UJhydmapy69wUaFog-dUt3lI1MbNW2wj

**Comment by nicongger** [comment]
> Use this one: https://drive.google.com/uc?id=1UJhydmapy69wUaFog-dUt3lI1MbNW2wj

thank you very much

**Comment by delldu** [comment]
This url seems out of valid, would you like share it again ? @nicongger , @FredWe , my thanks.

**Comment by FredWe** [comment]
> This url seems out of valid, would you like share it again ? @nicongger , @FredWe , my thanks.

https://huggingface.co/FredWe/01_MorphableModel.mat/resolve/main/01_MorphableModel.mat?download=true
