### ISSUE TITLE
`loss=nan` during training

### ISSUE THREAD

**Issue by Baiyixuan1113** [Fictionarry/ER-NeRF#12]
Hi,

I am trying to use your project to train custom face.

I found that when the input audio was changed into Chinese, the lips shape of the people in the output video did not correspond well. Therefore, I replaced the audio feature extraction module(wav2vec2) to support the Chinese from huggingface(`https://huggingface.co/wbbbbb/wav2vec2-large-chinese-zh-cn`), and I changed audio_in_dim to the corresponding number(`audio_in_dim = 5171`).

However, I encountered the situation of "loss=nan" in the process of training lip-finetuning, may I ask what might be the cause?

**Comment by Fictionarry** [comment]
The dimension of 5171 is too larger than the Esperanto version, and is likely no longer suitable to the current architecture. Moreover, not all extractor can be successfully applied to our task. HuBERT may performs better for chinese and you can have a try.

**Comment by Baiyixuan1113** [comment]
> The dimension of 5171 is too larger than the Esperanto version, and is likely no longer suitable to the current architecture. Moreover, not all extractor can be successfully applied to our task. HuBERT may performs better for chinese and you can have a try.

OK, thanks for your reply, I will  try.
