### ISSUE TITLE
head shaking is noticeable

### ISSUE THREAD

**Issue by SkyCol** [Fictionarry/ER-NeRF#18]
Compared to AD-nerf, I found the head shaking is noticeable, is there any way  have been found to improve this ?

**Comment by Fictionarry** [comment]
Adding `--smooth_path` may help when inference, which we inherit from RAD-NeRF.

**Comment by SkyCol** [comment]
> Adding `--smooth_path` may help when inference, which we inherit from RAD-NeRF.

Thank you! It's helpful

**Comment by SkyCol** [comment]
> Adding `--smooth_path` may help when inference, which we inherit from RAD-NeRF.

And when I do the lips finetune , I meet an error similar to https://github.com/Fictionarry/ER-NeRF/issues/13#issue-1836336970

Error: RuntimeError: Given input size: (192x3x2). Calculated output size: (192x1x0). Output size is too small

My video resolution is 476*476

**Comment by Fictionarry** [comment]
> > Adding `--smooth_path` may help when inference, which we inherit from RAD-NeRF.
> 
> And when I do the lips finetune , I meet an error similar to [#13 (comment)](https://github.com/Fictionarry/ER-NeRF/issues/13#issue-1836336970)
> 
> Error: RuntimeError: Given input size: (192x3x2). Calculated output size: (192x1x0). Output size is too small
> 
> My video resolution is 476*476

Well, I think it's because the lip rect is too small for LPIPS in some frames, and now I have done a fix about it, but not sure if it works for you :)

**Comment by SkyCol** [comment]
> Well, I think it's because the lip rect is too small for LPIPS in some frames, and now I have done a fix about it, but not sure if it works for you :)
Yes！the error is did not appear again , thank you for your help.

**Comment by SkyCol** [comment]
> > > Adding `--smooth_path` may help when inference, which we inherit from RAD-NeRF.
> > 
> > 
> > And when I do the lips finetune , I meet an error similar to [#13 (comment)](https://github.com/Fictionarry/ER-NeRF/issues/13#issue-1836336970)
> > Error: RuntimeError: Given input size: (192x3x2). Calculated output size: (192x1x0). Output size is too small
> > My video resolution is 476*476
> 
> Well, I think it's because the lip rect is too small for LPIPS in some frames, and now I have done a fix about it, but not sure if it works for you :)

Well, I think it's because the lip rect is too small for LPIPS in some frames, and now I have done a fix about it, but not sure if it works for you :)
Yes! the error did not appear again , thank you for your help.
