### ISSUE TITLE
About hubert Model

### ISSUE THREAD

**Issue by Rookie-Kai** [Fictionarry/ER-NeRF#20]
Is it necessary to retrain the model when using the audio features extracted by Hubert?
Because when I replaced the features extracted by Hubert, I found that the weights you provided could not be inferred, and the dimensions did not match.

>RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
	size mismatch for audio_net.encoder_conv.0.weight: copying a param with shape torch.Size([32, 29, 3]) from checkpoint, the shape in current model is torch.Size([32, 1024, 3]).

**Comment by SkyCol** [comment]
> Is it necessary to retrain the model when using the audio features extracted by Hubert? Because when I replaced the features extracted by Hubert, I found that the weights you provided could not be inferred, and the dimensions did not match.
> 
> > RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
> > size mismatch for audio_net.encoder_conv.0.weight: copying a param with shape torch.Size([32, 29, 3]) from checkpoint, the shape in current model is torch.Size([32, 1024, 3]).

hello, it is because the --asr_model params in main.py and your hu_bert.npy file does not match.

**Comment by SkyCol** [comment]
> Is it necessary to retrain the model when using the audio features extracted by Hubert? Because when I replaced the features extracted by Hubert, I found that the weights you provided could not be inferred, and the dimensions did not match.
> 
> > RuntimeError: Error(s) in loading state_dict for NeRFNetwork:
> > size mismatch for audio_net.encoder_conv.0.weight: copying a param with shape torch.Size([32, 29, 3]) from checkpoint, the shape in current model is torch.Size([32, 1024, 3]).

However , I have another question about this https://github.com/Fictionarry/ER-NeRF/issues/21#issue-1847207231

**Comment by Rookie-Kai** [comment]
> > 使用 Hubert 提取的音频特征时，是否需要重新训练模型？因为当我替换休伯特提取的特征时，我发现你提供的权重无法推断，尺寸不匹配。
> > > 运行时错误：加载 NeRFNetwork state_dict时出错：audio_net.encoder_conv.0.weight的大小不匹配：使用形状火炬复制参数。尺寸（[32， 29， 3]） 从检查点开始，当前模型中的形状是割炬。大小（[32， 1024， 3]）.
> 
> 您好，这是因为 main.py 中的 --asr_model 参数和您的 hu_bert.npy 文件不匹配。

Yes, so can you provide the hubert weights for your test, or how can I modify my hubert file? Or do I need to specify asr_model as hubert during training and re-train on Obama.mp4

**Comment by Fictionarry** [comment]
> Yes, so can you provide the hubert weights for your test, or how can I modify my hubert file? Or do I need to specify asr_model as hubert during training and re-train on Obama.mp4

The audio feature type should be the same both during training and testing, and the released checkpoint is trained with DeepSpeech to reproduce our experiment results. You need to retrain the model from scratch and specify the target feature type if you want to test other audio extractors.
