### ISSUE TITLE
No such file or directory: 'data/obama/track_params.pt'

### ISSUE THREAD

**Issue by BarryAlllen** [Fictionarry/ER-NeRF#31]
Hi, when I run the process_data.py, it shows me No such file or directory: 'data/obama/track_params.pt'.
How to fix it?

**Comment by pzc163** [comment]
I meet the same error，did u have fix it？

**Comment by BarryAlllen** [comment]
> I meet the same error，did u have fix it？
No, I haven't solved it yet.

**Comment by baijiesong** [comment]
> > I meet the same error，did u have fix it？
> > No, I haven't solved it yet.

Oh，me too，did u have fixed it？

**Comment by baijiesong** [comment]
> > > > I meet the same error，did u have fix it？
> > > > No, I haven't solved it yet.
> > 
> > 
> > Oh，me too，did u have fixed it？
> 
> Try reinstalling pytorch3d, my version is 0.7.4, and the torch version is 1.12.1+cu116.

thanks，I‘ll try it

**Comment by BarryAlllen** [comment]
I have summarized the deployment process of rad nerf, https://blog.csdn.net/BarryA11en/article/details/132894702?spm=1001.2014.3001.5501
