### ISSUE TITLE
How to obtain AU45 for eyes blinking?

### ISSUE THREAD

**Issue by chaolongy** [Fictionarry/ER-NeRF#39]
Run FeatureExtraction in [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace), rename and move the output CSV file to data/<ID>/au.csv.

I don't know the format of au.csv. Whether you have a processing script? Thank you for your timely reply.

**Comment by Fictionarry** [comment]
It is described by OpenFace that:
> By default the executable will output all features (tracked videos, HOG files, similarity aligned images **and a .csv file** with landmarks, action units and gaze). You might not always want to extract all the output features, you can specify the desired output using the following flags:

You can easily find the .csv file if you have once run OpenFace. Directly put it into the target folder and rename it.

**Comment by tailangjun** [comment]
如果是Linux环境，可以下载 OpenFace，然后运行 ./bin/FeatureExtraction -f <xxx.mp4> -out_dir <directory> -aus

**Comment by zhongtao93** [comment]
> 如果是Linux环境，可以下载 OpenFace，然后运行 ./bin/FeatureExtraction -f <xxx.mp4> -out_dir -aus

有遇到同一个视频使用FeatureExtraction得到的总帧数小于真实的情况么，我试了几次，一个长为59.88的视频，用FeatureExtraction跑完之后，csv的总时长只有58.84,帧数也少了几十帧。而我如果用ffmpeg把所有帧拆出来，每一帧用ffmpeg都是有结果的

**Comment by tailangjun** [comment]
> > 如果是Linux环境，可以下载 OpenFace，然后运行 ./bin/FeatureExtraction -f <xxx.mp4> -out_dir -aus
> 
> 有遇到同一个视频使用FeatureExtraction得到的总帧数小于真实的情况么，我试了几次，一个长为59.88的视频，用FeatureExtraction跑完之后，csv的总时长只有58.84,帧数也少了几十帧。而我如果用ffmpeg把所有帧拆出来，每一帧用ffmpeg都是有结果的

我这边看到的总帧数是一致的哟，下面是我的一个case
csv的表头：frame | face_id | timestamp
csv倒数第二行：1424 | 0 | 56.920
csv倒数第一行：1425 | 0 | 56.960
说明 csv中总帧数是 1425，总时长是57.000

查看视频的总帧数
$ ffprobe -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1 Teacher01.mp4
1425 
说明总帧数是一致的

查看视频的三个时长，他们可能都不相等
容器时长（container duration）
$ ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 -i Teacher01.mp4 
57.022000

查看视频的音视频流时长（stream duration）
$ ffprobe -v error -select_streams v:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 Teacher01.mp4 
57.000000

解码后文件播放时长（get duration by decoding）
$ ffmpeg -i Teacher01.mp4 -f null -
frame= 1425 fps=0.0 q=-0.0 Lsize=N/A time=00:00:57.00 bitrate=N/A speed= 437x
说明时长也是一致的

**Comment by feifeitu1** [comment]
请问一下你们openface的download_models是直接输命令下载的吗，连接了好几次都连不上

**Comment by FredWe** [comment]
> 请问一下你们openface的download_models是直接输命令下载的吗，连接了好几次都连不上

需要翻墙
