### ISSUE TITLE
处理自己的视频时报错 Bin size was too small in the coarse rasterization phase.

### ISSUE THREAD

**Issue by tailangjun** [Fictionarry/ER-NeRF#43]
Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.Bin size was too small in the coarse rasterization phase. This caused an overflow, meaning output may be incomplete. To solve, try increasing max_faces_per_bin / max_points_per_bin, decreasing bin_size, or setting bin_size to 0 to use the naive rasterization.

看英文是建议增加 max_faces_per_bin / max_points_per_bin，或者减小 bin_size。哪位大佬知道是怎么导致的，该怎样处理，谢谢

**Comment by NaMoCv** [comment]
bro，这个问题解决了吗？

**Comment by tailangjun** [comment]
解决了，是因为源视频中有部分帧脸部侧面倾斜太厉害，这些帧裁剪掉就好了

**Comment by kike-0304** [comment]
> 解决了，是因为源视频有部分帧头部发型太厉害了，这些帧修剪掉就好了

兄弟，发型太厉害是什么意思呀，是头发太乱了吗
