### ISSUE TITLE
你好，我在推理的时候身体部分图像错位，有小片的图像缺失，该怎么优化？能不能仅推理脸部，身体还是用原来的

### ISSUE THREAD

**Issue by a279780399** [Fictionarry/ER-NeRF#46]

**Comment by Fictionarry** [comment]
1）身体部分的缺失通常源自于parsing的错误

2）忽略torso阶段的训练和推理即可

**Comment by ligyvip** [comment]
> 1）身体部分的缺失通常源自于parsing的错误
> 
> 2）忽略torso阶段的训练和推理即可

如果是需要带身体，是不需要训练torso 和推理时候也不要带torso参数就可以了吗？

**Comment by Fictionarry** [comment]
> 如果是需要带身体，是不需要训练torso 和推理时候也不要带torso参数就可以了吗？

对的，但是parsing导致的错误仍会保留。若要完全保留原本的身体部分则需要修改预处理和provider.py中相应的部分，可以参考DFRF

**Comment by ligyvip** [comment]
> DFRF

https://github.com/sstzal/DFRF  这个吗？

**Comment by tailangjun** [comment]
错位的情况我也遇到了，貌似脖子周围有头发就容易出现，看到这个issue刚好学习一下

**Comment by a279780399** [comment]
> 1）身体部分的缺失通常源自于parsing的错误
> 
> 2）忽略torso阶段的训练和推理即可

感谢，你的回复，我将进行尝试
