### ISSUE TITLE
生成的视频贴回原图错位问题

### ISSUE THREAD

**Issue by Wentao795** [Fictionarry/ER-NeRF#54]
非常感谢您的工作。我在尝试训练自己的视频，生成图片贴回去的时候，碰到错位的问题，如下图，您能帮我看看吗？
![image](https://github.com/Fictionarry/ER-NeRF/assets/35397905/1bab3c36-f7d6-4b01-8aca-185b65a35428)

**Comment by Fictionarry** [comment]
只训练head的情况下的身体部分应与原图像完全一致，需要贴回原视频的话请跳过torso阶段并在推理时指定`--test_train`

**Comment by einsqing** [comment]
> 非常感谢您的工作。我在尝试训练自己的视频，生成图片贴回去的时候，碰到错位的问题，如下图，您能帮我看看吗？
> ![image](https://github.com/Fictionarry/ER-NeRF/assets/35397905/1bab3c36-f7d6-4b01-8aca-185b65a35428)
> 

大佬，你咋贴回去？是不是训练的视频从拍摄的视频里剪出来正方形的头训练，计算原来头的位置，然后生成之后再放到相应的位置？

**Comment by Wentao795** [comment]
> 只训练head的情况下的身体部分应与原图像完全一致，需要贴回原视频的话请跳过torso阶段并在推理时指定`--test_train`

目前就是只训练head，没有采用“”python main.py data/obama/ --workspace trial_obama_torso/ -O --torso --head_ckpt <head>.pth --iters 200000“” 这里的训练。并且在测试的时候是指定了 --test_train。但是还有这个问题。
我不太明白您说的跳过torso阶段，是指“”python main.py data/obama/ --workspace trial_obama_torso/ -O --torso --test --test_train --aud <audio>.npy“” 这里不用 --torso 吗？
我现在的测试命令是“”python main.py data/obama/ --workspace trial_obama_torso/ -O --torso --test --aud <audio>.npy“”
期待您的回复

**Comment by Wentao795** [comment]
> > 非常感谢您的工作。我在尝试训练自己的视频，生成图片贴回去的时候，碰到错位的问题，如下图，您能帮我看看吗？
> > ![image](https://github.com/Fictionarry/ER-NeRF/assets/35397905/1bab3c36-f7d6-4b01-8aca-185b65a35428)
> 
> 大佬，你咋贴回去？是不是训练的视频从拍摄的视频里剪出来正方形的头训练，计算原来头的位置，然后生成之后再放到相应的位置？

对的

**Comment by Fictionarry** [comment]
> 目前就是只训练head，没有采用“”python main.py data/obama/ --workspace trial_obama_torso/ -O --torso --head_ckpt .pth --iters 200000“” 这里的训练。并且在测试的时候是指定了 --test_train。但是还有这个问题。 我不太明白您说的跳过torso阶段，是指“”python main.py data/obama/ --workspace trial_obama_torso/ -O --torso --test --test_train --aud .npy“” 这里不用 --torso 吗？ 我现在的测试命令是“”python main.py data/obama/ --workspace trial_obama_torso/ -O --torso --test --aud .npy“” 期待您的回复

没有训练torso但在推理时加上`--torso`的正常表现应为只有头部而没有身体。可以检查一下parsing的结果，看看是否成功地把颈部和头部分开了
不希望修改代码的情况下最好参考obama样例的人像比例裁剪训练视频，以免出现一些不可预知的错误

**Comment by Wentao795** [comment]
好，我会检查下parsing ，非常感谢您的回复，我先close 这个issue 。
