### ISSUE TITLE
生成的视频没有声音

### ISSUE THREAD

**Issue by yq-xfl** [Fictionarry/ER-NeRF#56]
我训练完后，用音频进行测试，口型大致能对上，但是results里的mp4没有声音，可能是哪里的问题呢？

还有如何我用更大的分辨率，比如1024*1024的视频，是否可以进行训练呢？

**Comment by Fictionarry** [comment]
没有声音是正常情况，见https://github.com/Fictionarry/ER-NeRF/issues/9
目前的超参数不支持1024分辨率的训练，需要自己进行调整
