### ISSUE TITLE
have a problem installing pytorch3d

### ISSUE THREAD

**Issue by zhuyang2356** [Fictionarry/ER-NeRF#68]
My cuda version is 11.4
I use the following commands:

conda create -n ernerf python=3.10
conda activate ernerf
conda install pytorch==1.12.1 torchvision==0.13.1 cudatoolkit=11.3 -c pytorch

cd pathToProject
git clone https://github.com/Fictionarry/ER-NeRF.git
cd ER-NeRF-main

#install pyaudio having a problem, using the following commands to achieve success.
apt-get update
apt-get install portaudio19-dev
apt-get install python3-all-dev
pip install pyaudio -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

while using this command to install pytorch3d, 
pip install "git+https://github.com/facebookresearch/pytorch3d.git"
have these errors:

copying pytorch3d/datasets/r2n2/r2n2_synset_dict.json -> build/lib.linux-x86_64-cpython-310/pytorch3d/datasets/r2n2
      running build_ext
      error: [Errno 2] No such file or directory: '/usr/local/cuda/bin/bin/nvcc'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch3d
  Running setup.py clean for pytorch3d
Failed to build pytorch3d
ERROR: Could not build wheels for pytorch3d, which is required to install pyproject.toml-based projects

I thought the problem may be because the pytorch3d version has changed, can author give details of the pytorch3d? Or author can have a solution?

**Comment by zhuyang2356** [comment]
i changed my enviroment variable cuda_home from /usr/local/cuda/bin to /usr/local/cuda, and it works.
I will follow and see if things have any futher problems.

**Comment by nicongger** [comment]
`conda install -c fvcore -c iopath -c conda-forge fvcore iopath`
`conda install pytorch3d -c pytorch3d -c pytorch -c conda-forge`
