### ISSUE TITLE
训练完head后，test出来的视频，前几帧，人的嘴部是张开的，可能是什么原因？

### ISSUE THREAD

**Issue by husthzy** [Fictionarry/ER-NeRF#73]
用另外一个人的视频进行训练是正常的，但是这两个训练视频并没有什么区别，都是类似的绿幕背景说话人视频

**Comment by husthzy** [comment]
最后一个epoch数据的原因

**Comment by 641402676** [comment]
请问嘴部是张开是什么原因    困扰了我两天了

**Comment by vipxiaoma** [comment]
> 最后一个epoch数据的原因

@husthzy 能否详细说一下，我也遇到相同问题
